package com.micro.product.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "Size")
@Setter
public class Size {

    private String id;
    //private String sizeId;
    private String sizeName;

    public Size(){}

//    @DynamoDBRangeKey
//    public String getSizeId() {
//        return sizeId;
//    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    @DynamoDBAttribute
    public String getSizeName() {
        return sizeName;
    }
}
